# -*- coding: utf-8 -*-
"""Data Science - Graficos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1myO3V2WCb4Lw4XLDHHLI957csg1UPbCI

# Imports
"""

from random import randrange, seed

seed(11)

randrange(0, 11)

notas_matematica = []

for notas in range(8):
  notas_matematica.append(randrange(0, 11))

notas_matematica

"""# Matplotlib"""

import matplotlib.pyplot as plt

x = list(range(1, 9))
y = notas_matematica
plt.plot(x, y, marker='o')
plt.title('Notas de Matemática')
plt.xlabel('Provas')
plt.ylabel('Notas')
plt.show()

import pandas as pd
notas = pd.read_csv('ratings.csv')
notas.head()

notas.shape #retorna a quantidade de linhas e colunas

notas.columns = ['usuarioId', 'filmeId', 'nota', 'momento']
notas.head() #Retonra os valores das primeiras n linhas

notas['Nota'].unique()

notas.nota.value_counts()

print('Média: ', notas['nota'].mean())
print('Mediana: ', notas['nota'].median())

notas.nota.head()

notas.nota.plot(kind='hist')

notas.nota.describe()

filmes = pd.read_csv('movies.csv')
filmes.columns = ['filmeId', 'titulo', 'generos']
filmes.head()

notas.head()

